### ISSUE TITLE
Remap suitable for RZ (Cylindrical co-ordinates)

### ISSUE THREAD

**Issue by cjoycd** [CEED/Remhos#20]
Dear contributors,

I have been using the modified version of Laghos by implementing RZ (Cylindrical) geometry as well as multi-material formulations. Presently looking forward to implement a remap scheme using REMHOS miniapp. As far as I can understand, the RZ capability is not implemented with the present REMHOS version. I would like to know is there any future version planned to include this capability ? What are the changes that might required to make it compatible with RZ geometry (like changes in Convection Integrator,  Mass Integrator, Trace Integrators, ....) ? Is there any documentation available ?

Thank you in advance
-- Sijoy

**Comment by vladotomov** [comment]
Hi Sijoy,

You're right, there is no RZ capability in Remhos. We don't plan to add this to the miniapp. We will also stick to a single-material formulation, to reduce complexity.

There is a branch (product-sync) that implements product remap, e.g., remapping mass while preserving the bounds of density. This is one approach to connect Laghos and Remhos, as derived in our [ALE paper](https://epubs.siam.org/doi/10.1137/17M1116453). This branch is still WIP, but it will be merged soon.

The only change to make RZ work would be to add the extra weight coefficient to all integrators. I expect that most methods won't require any other manipulations, although I haven't looked closely at all of them.

Vladimir

**Comment by cjoycd** [comment]
Dear Vladimir,

Thank you for comments. 
I will look forward to the version with (product-sync) that implements product remap and try to make the changes for RZ compatibility.  

Regards
