### ISSUE TITLE
regarding low order elements (order<2)

### ISSUE THREAD

**Issue by sungho91** [CEED/Remhos#43]
Hi all,

I have a quick question
Can we make Remhos work for low-order elements like (order<2)?

Best,

Sungho

**Comment by vladotomov** [comment]
@sungho91 it's supposed to work with `-o 1`, and even probably with `-o 0`.

**Comment by sungho91** [comment]
@vladotomov 

Really?  If I command line like this `mpirun -np 8 remhos -m ./data/cube01_hex.mesh -p 10 -rs 1 -o 1`, it does not work.
Also, I turned off the high-order solver by setting zero for the option and tried every option for the low-order solver, but it eventually was terminated.

**Comment by vladotomov** [comment]
You are correct, there are somme inaccuracies in the setup.

Please try #45 and let me knows if it works.

**Comment by sungho91** [comment]
@vladotomov 

I used `mpirun -np 8 remhos -m ./data/cube01_hex.mesh -p 10 -rs 2 -o 1 -dt 0.02 -tf 0.8 -ho 1 -lo 1 -fct 2 -visit` or  `mpirun -np 8 remhos -m ./data/cube01_hex.mesh -p 10 -rs 1 -o 2 -dt 0.02 -tf 0.8 -ho 1 -lo 1 -fct 2 -visit`  and got those result. They look similar so, I think it wroks correctly.


By the way, since Remhos has some options for choosing solvers, do we have the best options for running Remhos as a rule of thumb? 


![visit0001](https://github.com/CEED/Remhos/assets/40257026/8ba6e276-b9b5-4b3c-aa01-4768f298f7e0)

![visit0000](https://github.com/CEED/Remhos/assets/40257026/4e775c15-35ce-4c1c-bd34-8fa8c64ea303)

**Comment by vladotomov** [comment]
> By the way, since Remhos has some options for choosing solvers, do we have the best options for running Remhos as a rule of thumb?

For orders up to two, with standard matrix-based assembly, I'd say the best (sharpest / most robust / most tested) option is
`-ho 3 -lo 2 -fct 1`
